"""add valid_until to price levels

Revision ID: 881378450e4e
Revises: 3ac843934e46
Create Date: 2026-09-21 19:21:53.609670+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881378450e4e'
down_revision: Union[str, None] = '3ac843934e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_level_history_entries', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('price_levels', sa.Column('valid_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_levels', 'valid_until')
    op.drop_column('price_level_history_entries', 'valid_until')
    # ### end Alembic commands ###
