"""market and fx price history tables (Spec D09)

Revision ID: 0bcca54d1f74
Revises: 27b246d96728
Create Date: 2026-06-23 10:41:05.619375+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcca54d1f74'
down_revision: Union[str, None] = '27b246d96728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_currency', 'base_currency', 'as_of_date', name='uq_fx_pair_date')
    )
    op.create_table('asset_price_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('provider', sa.Enum('twelve_data', 'finnhub', name='market_provider_enum'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'as_of_date', name='uq_asset_price_date')
    )
    op.create_index(op.f('ix_asset_price_history_asset_id'), 'asset_price_history', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_price_history_asset_id'), table_name='asset_price_history')
    op.drop_table('asset_price_history')
    op.drop_table('fx_rate_history')
    # ### end Alembic commands ###
