"""add amount_type to asset_dividend_schedules

Revision ID: 3ac843934e46
Revises: 279c4995d04e
Create Date: 2026-07-17 10:18:04.911318+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac843934e46'
down_revision: Union[str, None] = '279c4995d04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_amount_type_enum = sa.Enum('nominal', 'percentage', name='dividend_amount_type_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike op.create_table (which auto-creates enum types found in its
    # columns), op.add_column does NOT create the Postgres type for you —
    # it has to be created explicitly first, or the ALTER TABLE fails with
    # UndefinedObject.
    _amount_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('asset_dividend_schedules', sa.Column('amount_type', _amount_type_enum, server_default='nominal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_dividend_schedules', 'amount_type')
    _amount_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
