"""d03-assets-holdings-lots-sales

Revision ID: b45761b05d68
Revises: 7473b32bbf86
Create Date: 2026-06-21 11:02:29.679908+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45761b05d68'
down_revision: Union[str, None] = '7473b32bbf86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('stock', 'etf', 'fund', 'crypto', name='asset_type_enum'), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uq_holding_portfolio_asset')
    )
    op.create_index(op.f('ix_holdings_asset_id'), 'holdings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_rate_at_purchase', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_origin', sa.Enum('auto', 'manual', 'corrected', 'manual_pending', name='fx_rate_origin_enum'), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quantity_consumed', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_holding_id'), 'lots', ['holding_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_rate_at_sale', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_origin', sa.Enum('auto', 'manual', 'corrected', 'manual_pending', name='fx_rate_origin_enum'), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_holding_id'), 'sales', ['holding_id'], unique=False)
    op.create_table('sale_lot_consumptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_lot_consumptions_lot_id'), 'sale_lot_consumptions', ['lot_id'], unique=False)
    op.create_index(op.f('ix_sale_lot_consumptions_sale_id'), 'sale_lot_consumptions', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_lot_consumptions_sale_id'), table_name='sale_lot_consumptions')
    op.drop_index(op.f('ix_sale_lot_consumptions_lot_id'), table_name='sale_lot_consumptions')
    op.drop_table('sale_lot_consumptions')
    op.drop_index(op.f('ix_sales_holding_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_lots_holding_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_asset_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
