"""D05 indicator catalog and snapshots

Revision ID: 3b7894bfc3df
Revises: 0bcca54d1f74
Create Date: 2026-06-23 13:02:33.176171+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7894bfc3df'
down_revision: Union[str, None] = '0bcca54d1f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_key', sa.String(length=128), nullable=False),
    sa.Column('description_key', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.Enum('asset', 'portfolio', name='indicator_scope_enum'), nullable=False),
    sa.Column('nature', sa.Enum('technical', 'fundamental', 'portfolio_kpi', name='indicator_nature_enum'), nullable=False),
    sa.Column('data_type', sa.Enum('quantitative', 'qualitative', name='indicator_data_type_enum'), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('calculator_code', sa.String(length=64), nullable=False),
    sa.Column('ai_extraction_key', sa.String(length=64), nullable=True),
    sa.Column('update_strategy', sa.Enum('scheduled_daily', 'on_ai_analysis', 'on_demand_calculated', name='indicator_update_strategy_enum'), nullable=False),
    sa.Column('threshold_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_code'), 'indicators', ['code'], unique=True)
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.Enum('asset', 'portfolio', name='snapshot_subject_type_enum'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('value_text', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('scheduled_job', 'ai_analysis', 'on_demand_calc', 'manual_override', name='snapshot_source_enum'), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'subject_id', 'as_of_date', name='uq_snapshot_indicator_subject_date')
    )
    op.create_index(op.f('ix_indicator_snapshots_indicator_id'), 'indicator_snapshots', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_indicator_snapshots_subject_id'), 'indicator_snapshots', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicator_snapshots_subject_id'), table_name='indicator_snapshots')
    op.drop_index(op.f('ix_indicator_snapshots_indicator_id'), table_name='indicator_snapshots')
    op.drop_table('indicator_snapshots')
    op.drop_index(op.f('ix_indicators_code'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
