"""analysis jobs and reports (Spec D07)

Revision ID: 7bbb11088877
Revises: 3b7894bfc3df
Create Date: 2026-06-23 14:47:51.716635+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bbb11088877'
down_revision: Union[str, None] = '3b7894bfc3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_holding_id'), 'uploaded_files', ['holding_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('anthropic', 'openai', 'gemini', name='ai_provider_enum'), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='analysis_job_status_enum'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('analysis_report_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_holding_id'), 'analysis_jobs', ['holding_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_file_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_job_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('provider', sa.Enum('anthropic', 'openai', 'gemini', name='ai_provider_enum'), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('extracted_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('global_signal', sa.Enum('bullish', 'neutral', 'bearish', name='global_signal_enum'), nullable=True),
    sa.Column('confidence_notes', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_holding_id'), 'analysis_reports', ['holding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_reports_holding_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_analysis_jobs_holding_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_holding_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
