"""add dividend tracking (asset_dividend_schedules, dividend_payments)

Revision ID: 279c4995d04e
Revises: d23ce764969d
Create Date: 2026-07-17 08:15:51.655345+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '279c4995d04e'
down_revision: Union[str, None] = 'd23ce764969d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # fx_rate_origin_enum was already created by the D03 migration (Lot/Sale
    # tables) — reused here for DividendPayment. create_type=False stops
    # Alembic from re-issuing CREATE TYPE (which would fail with
    # DuplicateObject, since the enum's shared Python object doesn't know it
    # was already materialized in a previous, unrelated migration).
    op.create_table('asset_dividend_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('monthly', 'quarterly', 'semiannual', 'annual', 'irregular', name='dividend_frequency_enum'), nullable=False),
    sa.Column('amount_per_payment', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('origin', sa.Enum('manual', 'auto', name='dividend_schedule_origin_enum'), server_default='manual', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_dividend_schedules_asset_id'), 'asset_dividend_schedules', ['asset_id'], unique=True)
    op.create_table('dividend_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('gross_amount_quote', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_rate_at_payment', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_origin', postgresql.ENUM('auto', 'manual', 'corrected', 'manual_pending', name='fx_rate_origin_enum', create_type=False), server_default='manual', nullable=False),
    sa.Column('gross_amount_base', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_payments_holding_id'), 'dividend_payments', ['holding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividend_payments_holding_id'), table_name='dividend_payments')
    op.drop_table('dividend_payments')
    op.drop_index(op.f('ix_asset_dividend_schedules_asset_id'), table_name='asset_dividend_schedules')
    op.drop_table('asset_dividend_schedules')
    # ### end Alembic commands ###
