"""add realized gain fields to sales

Revision ID: d23ce764969d
Revises: ec9e25367f5e
Create Date: 2026-07-15 22:15:12.552547+00:00

Backfill (Changeset C20 §1): for every existing Sale, if it has
SaleLotConsumption rows, compute the four realized-gain fields from them
(same FIFO formula as SaleService.create_sale — D13 §3, §4.1). Sales with no
consumption history, or whose consumed lots/sale lack an fx_rate needed for
the base-currency figures, are left NULL and logged as a warning rather than
silently skipped (Spec 00c — no silent data loss).
"""
import logging
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23ce764969d'
down_revision: Union[str, None] = 'ec9e25367f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger(__name__)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('cost_basis_quote', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('sales', sa.Column('cost_basis_base', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('sales', sa.Column('realized_gain_quote', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('sales', sa.Column('realized_gain_base', sa.Numeric(precision=18, scale=8), nullable=True))
    # ### end Alembic commands ###

    _backfill_realized_gain_fields()


def _backfill_realized_gain_fields() -> None:
    bind = op.get_bind()

    sales = bind.execute(
        sa.text("SELECT id, quantity, unit_price, fx_rate_at_sale FROM sales")
    ).fetchall()

    backfilled = 0
    for sale_id, quantity, unit_price, fx_rate_at_sale in sales:
        consumptions = bind.execute(
            sa.text(
                """
                SELECT c.quantity_consumed, l.unit_price, l.fx_rate_at_purchase
                FROM sale_lot_consumptions c
                JOIN lots l ON l.id = c.lot_id
                WHERE c.sale_id = :sale_id
                """
            ),
            {"sale_id": sale_id},
        ).fetchall()

        if not consumptions:
            logger.warning(
                "Sale %s has no SaleLotConsumption rows — cannot backfill "
                "realized-gain fields, leaving them NULL.", sale_id,
            )
            continue

        cost_basis_quote = sum(
            (qty * lot_price for qty, lot_price, _ in consumptions), Decimal("0")
        )
        realized_gain_quote = (quantity * unit_price) - cost_basis_quote

        cost_basis_base = None
        realized_gain_base = None
        if fx_rate_at_sale is not None and all(lot_fx is not None for _, _, lot_fx in consumptions):
            cost_basis_base = sum(
                (qty * lot_price * lot_fx for qty, lot_price, lot_fx in consumptions),
                Decimal("0"),
            )
            realized_gain_base = (quantity * unit_price * fx_rate_at_sale) - cost_basis_base
        else:
            logger.warning(
                "Sale %s is missing fx_rate_at_sale or a consumed lot's "
                "fx_rate_at_purchase — base-currency fields left NULL "
                "(quote-currency fields were still backfilled).", sale_id,
            )

        bind.execute(
            sa.text(
                """
                UPDATE sales
                SET cost_basis_quote = :cbq,
                    cost_basis_base = :cbb,
                    realized_gain_quote = :rgq,
                    realized_gain_base = :rgb
                WHERE id = :sale_id
                """
            ),
            {
                "cbq": cost_basis_quote,
                "cbb": cost_basis_base,
                "rgq": realized_gain_quote,
                "rgb": realized_gain_base,
                "sale_id": sale_id,
            },
        )
        backfilled += 1

    logger.info(
        "Realized-gain backfill: %d of %d existing sale(s) backfilled.",
        backfilled, len(sales),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'realized_gain_base')
    op.drop_column('sales', 'realized_gain_quote')
    op.drop_column('sales', 'cost_basis_base')
    op.drop_column('sales', 'cost_basis_quote')
    # ### end Alembic commands ###
