"""add volume to asset_price_history

Revision ID: 958d0a9f0634
Revises: 7bbb11088877
Create Date: 2026-06-26 03:42:42.025865+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958d0a9f0634'
down_revision: Union[str, None] = '7bbb11088877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_price_history', sa.Column('volume', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_price_history', 'volume')
    # ### end Alembic commands ###
