"""d12 cascade failure reports

Revision ID: d8b2945bc077
Revises: 7970fe6dc6bd
Create Date: 2026-07-03 12:50:46.298147+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b2945bc077'
down_revision: Union[str, None] = '7970fe6dc6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cascade_failure_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_assets_processed', sa.Integer(), nullable=False),
    sa.Column('resolved_by_provider', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cascade_failure_reports_run_completed_at'), 'cascade_failure_reports', ['run_completed_at'], unique=False)
    op.create_table('cascade_failure_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Enum('not_found', 'rate_limited', 'insufficient_lookback', 'provider_error', name='cascade_failure_reason_enum'), nullable=False),
    sa.Column('providers_tried', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error_by_provider', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['cascade_failure_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cascade_failure_entries_asset_id', 'cascade_failure_entries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cascade_failure_entries_report_id'), 'cascade_failure_entries', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cascade_failure_entries_report_id'), table_name='cascade_failure_entries')
    op.drop_index('ix_cascade_failure_entries_asset_id', table_name='cascade_failure_entries')
    op.drop_table('cascade_failure_entries')
    op.drop_index(op.f('ix_cascade_failure_reports_run_completed_at'), table_name='cascade_failure_reports')
    op.drop_table('cascade_failure_reports')
    # ### end Alembic commands ###
    # Manually added: autogenerate creates this enum type implicitly via the
    # 'reason' column but does not drop it on downgrade, leaving it orphaned.
    postgresql.ENUM(name='cascade_failure_reason_enum').drop(op.get_bind(), checkfirst=True)
