"""add alert_seen_at to price_levels

Revision ID: b6cb0ba24c3c
Revises: 134373cf7b3e
Create Date: 2026-07-09 10:29:40.176285+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cb0ba24c3c'
down_revision: Union[str, None] = '134373cf7b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_levels', sa.Column('alert_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_levels', 'alert_seen_at')
    # ### end Alembic commands ###
