"""price levels and analysis history -- Spec D06

Revision ID: 27b246d96728
Revises: b45761b05d68
Create Date: 2026-06-23 09:25:49.332559+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b246d96728'
down_revision: Union[str, None] = 'b45761b05d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_level_history_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('originating_level_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'edited', 'touched', 'removed', name='price_level_event_type_enum'), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('direction', sa.Enum('buy', 'sell', name='price_level_direction_enum'), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('asset_price_at_event', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plhe_holding_id', 'price_level_history_entries', ['holding_id'], unique=False)
    op.create_index('ix_plhe_originating_level_id', 'price_level_history_entries', ['originating_level_id'], unique=False)
    op.create_table('price_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('buy', 'sell', name='price_level_direction_enum'), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('armed', 'touched', name='price_level_status_enum'), server_default='armed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('touched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('touched_at_close_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('touched_at_close_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_levels_holding_id'), 'price_levels', ['holding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_levels_holding_id'), table_name='price_levels')
    op.drop_table('price_levels')
    op.drop_index('ix_plhe_originating_level_id', table_name='price_level_history_entries')
    op.drop_index('ix_plhe_holding_id', table_name='price_level_history_entries')
    op.drop_table('price_level_history_entries')
    # ### end Alembic commands ###
